services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    privileged: true
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


  agent:
    image: adijida/agent:latest
    #image: agent
    container_name: agent-api
    restart: always
    depends_on:
      - mongodb
      - ollama
    env_file:
      - dockerEnvironmentVariables.env
    ports:
      - "5000:5000"

volumes:
  mongo-data:
    driver: local
  ollama-data: